export const FETCH_POSTS = "FETCH_POSTS";
export const FETCH_POSTS_REQ = "FETCH_POSTS_REQ";
export const FETCH_POSTS_SUC = "FETCH_POSTS_SUC";
export const FETCH_POSTS_FAIL = "FETCH_POSTS_FAIL";

export const FETCH_ONE_POST = "FETCH_ONE_POST";
export const FETCH_ONE_POST_REQ = "FETCH_ONE_POST_REQ";
export const FETCH_ONE_POST_SUC = "FETCH_ONE_POST_SUC";
export const FETCH_ONE_POST_FAIL = "FETCH_ONE_POST_FAIL";

export const DELETE_ONE_POST = "DELETE_ONE_POST";
export const DELETE_ONE_POST_REQ = "DELETE_ONE_POST_REQ";
export const DELETE_ONE_POST_SUC = "DELETE_ONE_POST_SUC";
export const DELETE_ONE_POST_FAIL = "DELETE_ONE_POST_FAIL";

export const ADD_ONE_POST = "ADD_ONE_POST";
export const ADD_ONE_POST_REQ = "ADD_ONE_POST_REQ";
export const ADD_ONE_POST_SUC = "ADD_ONE_POST_SUC";
export const ADD_ONE_POST_FAIL = "ADD_ONE_POST_FAIL";
