export const FETCH_POSTS = "FETCH_POSTS";
export const FETCH_POSTS_REQ = "FETCH_POSTS_REQ";
export const FETCH_POSTS_SUC = "FETCH_POSTS_SUC";
export const FETCH_POSTS_FAIL = "FETCH_POSTS_FAIL";

export const FETCH_ONE_POST = "FETCH_ONE_POST";
export const FETCH_ONE_POST_REQ = "FETCH_ONE_POST_REQ";
export const FETCH_ONE_POST_SUC = "FETCH_ONE_POST_SUC";
export const FETCH_ONE_POST_FAIL = "FETCH_ONE_POST_FAIL";

export const FIND_ONE_POST_REQ = "FIND_ONE_POST_REQ";
export const FIND_ONE_POST_SUC = "FIND_ONE_POST_SUC";
export const FIND_ONE_POST_FAIL = "FIND_ONE_POST_FAIL";
export const REMOVE_ONE_POST_SUC = "REMOVE_ONE_POST_SUC";

export const DELETE_ONE_POST_REQ = "DELETE_ONE_POST_REQ";
export const DELETE_ONE_POST_SUC = "DELETE_ONE_POST_SUC";
export const DELETE_ONE_POST_FAIL = "DELETE_ONE_POST_FAIL";
